### ISSUE TITLE
Render Search Results In PostCard For Mobile App

### ISSUE THREAD

**Issue by erenpakelgil** [bounswe/bounswe2024group7#104]
## Title:
Render Search Results In PostCard For Mobile App

## Category:
- [x] Feature Request
- [ ] Enhancement
- [ ] Design Proposal
- [ ] Specification Clarification
- [ ] Planning Discussion

## Objective:
To be able to display items resulting from POST requests in PostCard components [#92]  

### Overview
Currently, PostCard component uses mock data. It is a necessity for being able to use actual data coming from Wikidata API provided by the backend side and render it properly to the component.

**Comment by m1u1s1** [comment]
Project Archived.
