### ISSUE TITLE
Access Profile Page via Feed Page

### ISSUE THREAD

**Issue by MertCengiz** [bounswe/bounswe2024group7#108]
## Title:
Access Profile Page via Feed Page

## Category:
- [x] Feature Request
- [x] Enhancement
- [ ] Design Proposal
- [ ] Specification Clarification
- [ ] Planning Discussion

## Objective:
To be able to access the profile page in the feed page, to put a button so that users may access the profile page from the feed page.

### Overview
Currently, it is impossible to access the profile page in our application. According to our Mock-ups, users access it via a button in his/her feed page. 

### Proposed Restructuring:
1. **Adding New Button**:
   - Create a new button named same as the username within App.js file, instead of just displaying the text containing username.
   - Connect this button to the newly created Profile Page.

### Implementation Considerations:
- Redirect to the correct page so that users do not get lost in the application.

**Comment by MertCengiz** [comment]
We are not currently able to go to the profile page by navigating but we are going to the home page.

**Comment by m1u1s1** [comment]
Project Archived.
