### ISSUE TITLE
Enhance semantic browsing through post view page on Mobile

### ISSUE THREAD

**Issue by hanazaq** [bounswe/bounswe2024group7#110]
when you click on post's label, it makes a search call for posts that have the same label value. 
e.g. click on label (material: oil) returns post cards that also have (material: oil) label.

**Comment by hanazaq** [comment]
@sametaln please consider this feature for web part as well.

**Comment by hanazaq** [comment]
Unfortunately, we were unable to implement this part before the deadline, and it has been highlighted by the professor as a crucial component for semantic browsing.

**Comment by m1u1s1** [comment]
Project Archived.
