### ISSUE TITLE
Update the Requirements with New Features

### ISSUE THREAD

**Issue by MertCengiz** [bounswe/bounswe2024group7#130]
## Title:
Update the Requirements with New Features

## Category:
- [ ] Feature Request
- [ ]  Enhancement
- [x]  Design Proposal
- [x]  Specification Clarification
- [ ]  Planning Discussion

## Objective
Improve the [Requirements](https://github.com/bounswe/bounswe2024group7/wiki/Requirements-of-the-New-Project) page according to the conclusions in the [Meeting 3](https://github.com/bounswe/bounswe2024group7/wiki/Meeting-Notes-%233).

## Links to relevant documentation or previous discussions
The initial [Requirements](https://github.com/bounswe/bounswe2024group7/wiki/Requirements-of-the-New-Project) is available.

## Detailed Description:
New features are decided to be added to the project in [Meeting 3](https://github.com/bounswe/bounswe2024group7/wiki/Meeting-Notes-%233). As they are not included in the [Requirements](https://github.com/bounswe/bounswe2024group7/wiki/Requirements-of-the-New-Project) right now, they must be added as soon as possible; in other words, [Requirements](https://github.com/bounswe/bounswe2024group7/wiki/Requirements-of-the-New-Project) must be updated.

## Impact Analysis:
- Clearly show the path that the project will follow
- Describe the boundaries that the project will have
- Enlighten the designing phase

## Related Team Members:
- Eren Pakelgil @erenpakelgil 
- Mert Cengiz @MertCengiz 

## Proposed Timeline:
Until 08/10/2024, the updated version of [Requirements](https://github.com/bounswe/bounswe2024group7/wiki/Requirements-of-the-New-Project) must be ready in order to review.

## Next Steps:
Update the [Requirements](https://github.com/bounswe/bounswe2024group7/wiki/Requirements-of-the-New-Project) if necessary in later stages.

**Comment by MertCengiz** [comment]
New version of [Requirements](https://github.com/bounswe/bounswe2024group7/wiki/Requirements-of-the-New-Project) is available right now. The updates are performed according to the discussions in the [Second Lab](https://github.com/bounswe/bounswe2024group7/wiki/Lab-Report-%232). There might be some points are missed to add, or overseen; therefore, a review from a second eye is a necessity. It would be effective if @erenpakelgil performs the review and necessary alterations if needed. Not closing this issue as **review needed**

**Comment by erenpakelgil** [comment]
Reviewed previous version of [Requirements](https://github.com/bounswe/bounswe2024group7/wiki/Requirements-of-the-New-Project) and edited/added necessary parts according to last meeting notes such as the addition of diet programs with content details, updates in registered user and personal pages requirements, collecting program related reqs under a separate "Program" header. Since there might be some reqs missing or misphrased, further review would be preferable.

**Comment by oguzhekim** [comment]
Updated [requirements](https://github.com/bounswe/bounswe2024group7/wiki/Requirements-of-the-New-Project) during lab hour w/@erenpakelgil

**Comment by MertCengiz** [comment]
Updated [Requirements](https://github.com/bounswe/bounswe2024group7/wiki/Requirements-of-the-New-Project) aiming it covers not only bodybuilding but also cardio. Closing this issue as for this stage, our  [Requirements](https://github.com/bounswe/bounswe2024group7/wiki/Requirements-of-the-New-Project) are sufficient. Additional work may performed under a newly created issue in the future.
