### ISSUE TITLE
Contribute and Update Use Case Scenarios

### ISSUE THREAD

**Issue by m1u1s1** [bounswe/bounswe2024group7#131]
## Title:
Update the Requirements with New Features

## Category:
- [ ] Feature Request
- [ ]  Enhancement
- [x]  Design Proposal
- [x]  Specification Clarification
- [ ]  Planning Discussion

## Objective
Create and contribute to the [Scenarios](https://github.com/bounswe/bounswe2024group7/wiki/Use-Case-Scenarios(draftv2)) page according to the conclusions in the [Meeting 3](https://github.com/bounswe/bounswe2024group7/wiki/Meeting-Notes-%233).

## Links to relevant documentation or previous discussions
The initial [Scenarios](https://github.com/bounswe/bounswe2024group7/wiki/Use-Case-Scenarios(draftv2)) is created before.

## Detailed Description:
New features are decided to be added to the project in [Meeting 3](https://github.com/bounswe/bounswe2024group7/wiki/Meeting-Notes-%233). 

## Impact Analysis:
- Help in clearly defining the requirements from the perspective of the user, ensuring that the system fulfills user needs.
- Provide a common language for stakeholders, developers, and testers to understand the system's functionality and expected behaviors.

## Related Team Members:
- Mustafa Ocak @m1u1s1  
- Asim Dag @aasimdag  

## Proposed Timeline:
Until 08/10/2024

**Comment by m1u1s1** [comment]
New version of [Scenarios](https://github.com/bounswe/bounswe2024group7/wiki/Use-Case-Scenarios(draftv2)) is available right now. The initial version are created according to the discussions in the [Second Lab](https://github.com/bounswe/bounswe2024group7/wiki/Lab-Report-%232). There might be some points are missed to add, or overseen; therefore, a review from a second eye is a necessity. It would be effective if @aasimdag  performs the review and necessary alterations if needed. Not closing this issue as **review needed**

**Comment by aasimdag** [comment]
In third lab, added some new scenarios and reviewed the previous ones. 
LGTM, Scenarios are ready for now. Closing the issue.
