### ISSUE TITLE
Initialize (Infrastructure) API 

### ISSUE THREAD

**Issue by m1u1s1** [bounswe/bounswe2024group7#133]
## Title:
Initialize API using spring framework 

## Category:
- [ ] Feature Request
- [x] Implementation
- [ ]  Enhancement
- [ ]  Design Proposal
- [ ]  Specification Clarification
- [ ]  Planning Discussion

## Objective
Create initial(demo) api using spring framework.

## Detailed Description:
New endpoints and features will be decided/added according to [Meeting 4](https://github.com/bounswe/bounswe2024group7/wiki/Meeting-Notes-%233). 

## Impact Analysis:
- Start with demo api and test the infrastructure with relevant part like, backend, frontend and mobile.

## Related Team Members:
- Mustafa Ocak @m1u1s1  
- Oguz Hekim @oguzhekim 
- Hanaa Zaqout @hanazaq 

## Proposed Timeline:
Until 15/10/2024

**Comment by sametaln** [comment]
API is initialized. We can close this issue. @oguzhekim
