### ISSUE TITLE
Initialize DB using Postgresql

### ISSUE THREAD

**Issue by m1u1s1** [bounswe/bounswe2024group7#135]
## Title:
Initialize DB and connect to backend, using postgresql/

## Category:
- [ ] Feature Request
- [x] Implementation
- [ ]  Enhancement
- [ ]  Design Proposal
- [ ]  Specification Clarification
- [ ]  Planning Discussion

## Objective
Create initial(demo) Db infrastructure.

## Detailed Description:
New columns and schemas will be implemented according to [Meeting 4](https://github.com/bounswe/bounswe2024group7/wiki/Meeting-Notes-%233). 

## Impact Analysis:
- Start with demo DB and test the infrastructure with relevant parts(backend).

## Related Team Members:
- Mustafa Ocak @m1u1s1  
- Oguz Hekim @oguzhekim 
- Hanaa Zaqout @hanazaq 

## Proposed Timeline:
Until 15/10/2024

**Comment by sametaln** [comment]
DB is initialized on both local and deployment server. We can close this issue.
