### ISSUE TITLE
Initialize Mobile Application

### ISSUE THREAD

**Issue by erenpakelgil** [bounswe/bounswe2024group7#136]
Title:
Issue created for initialization of mobile application.

Category:
- [x] Feature Request
- [ ]  Enhancement
- [ ]  Design Proposal
- [ ]  Specification Clarification
- [x]  Planning Discussion

Objective:
Create the basic functionalities of the mobile frontend application.

Detailed Description:
We should  such as creating mock components and connecting with API.

Related Team Members:
- Asım Dağ @aasimdag 
-  Mert Cengiz @MertCengiz 
-  Eren Pakelgil @erenpakelgil 

Proposed Timeline:
15.10.2024 - Not Strict

**Comment by MertCengiz** [comment]
Mobile application was initialized in a collaborative session with Eren Pakelgil @erenpakelgil. 
### Parts that are DONE
- Home, login, register, profile page, and post cards were initialized with mock data.
- As initialized with mock data, every username, password are accepted, and mock profiles and posts exist only
- Dockerfile in mobile part was prepared.
- docker.compose.yaml file was updated with the content of the mobile part.
### Parts that should be CONSIDERED
- Android Studio Emulator failed, so the parts done should be tested.
- docker.compose.yaml should be checked for the directory of the mobile application
- Profile page and feeding system should be improved according to the [Requirements](https://github.com/bounswe/bounswe2024group7/wiki/Requirements-of-the-New-Project)

**Comment by erenpakelgil** [comment]
New mobileApp folder and project files under it are pushed to a new branch. Corresponding PR will be created when the bug related to a mobile folder that is locked and cannot be removed from the root directory is fixed.

**Comment by MertCengiz** [comment]
Dockerfile and Mobile version of docker-compose.yaml files are added successfully. Closing this issue as mobile application is initialized.
