### ISSUE TITLE
Containerize DB, create docker image

### ISSUE THREAD

**Issue by m1u1s1** [bounswe/bounswe2024group7#137]
## Title:
Containerize DB, write docker file and create docker image for it.
Creating registry is optional but will be done before deployment.

## Category:
- [ ] Feature Request
- [x] Implementation
- [ ]  Enhancement
- [ ]  Design Proposal
- [ ]  Specification Clarification
- [ ]  Planning Discussion

## Objective
Write docker file for postgresql db. 

## Related Team Members:
- Mustafa Ocak @m1u1s1  
- Oguz Hekim @oguzhekim 
- Hanaa Zaqout @hanazaq 

## Proposed Timeline:
Until 15/10/2024

**Comment by sametaln** [comment]
Updated the implemented dockerfile and docker-compose file for deployment. Docker-compose configuration is in the root folder now.

**Comment by sametaln** [comment]
We can close this issue. Dockerization is done.
