### ISSUE TITLE
Proposing new planning issue template

### ISSUE THREAD

**Issue by sametaln** [bounswe/bounswe2024group7#14]
My proposal to improve our issue templates:

```md
Title:
A clear and concise title that encapsulates the planning topic or design issue.

Category:
- [ ] Feature Request
- [ ]  Enhancement
- [ ]  Design Proposal
- [ ]  Specification Clarification
- [ ]  Planning Discussion

Objective:
Briefly describe the goal or outcome you aim to achieve with this issue. This could be a feature to implement, a design problem to solve, or a concept that needs further discussion.

Background/Context:
Provide any background information that is necessary to understand the issue. This could include:

Links to relevant documentation or previous discussions
Summary of related work done by the team or in the industry
Explanation of how this issue fits into the overall project goals

Detailed Description:
Expand on the objective with a detailed description of what is being proposed, discussed, or clarified. Include the solutions you have considered and your questions.

Visuals:
Attach any visuals, mock-ups, diagrams, or wireframes that can help others understand your ideas or the issues being addressed. Visual aids are especially important in design discussions.

Impact Analysis:
Discuss the potential impact of this issue on the project, including:
How it might affect existing or planned features
Any risks or challenges that could arise
The benefits or improvements it promises

Related Team Members:
List the team members who should be involved in this discussion.

Discussion Points:
Explain specific points or questions you want feedback on.

Proposed Timeline:
If necessary, propose a timeline to discuss this 

Next Steps:
Explain what you have in your mind to improve the issue situation.
```

**Comment by sametaln** [comment]
Couldn't find `Create Issue Template` setting in our repository settings. Is there something I miss?

**Comment by aasimdag** [comment]
Didnt realise for a while, your template lgtm. maybe saving them as a page under templates section will be a solution?

**Comment by sametaln** [comment]
## Title:
A clear and concise title that encapsulates the planning topic or design issue.

## Category:
- [ ] Feature Request
- [ ]  Enhancement
- [ ]  Design Proposal
- [ ]  Specification Clarification
- [ ]  Planning Discussion

## Objective:
Briefly describe the goal or outcome you aim to achieve with this issue. This could be a feature to implement, a design problem to solve, or a concept that needs further discussion.

## Background/Context:
Provide any background information that is necessary to understand the issue. This could include:

## Detailed Description:
Expand on the objective with a detailed description of what is being proposed, discussed, or clarified. Include the solutions you have considered and your questions.

## Visuals:
Attach any visuals, mock-ups, diagrams, or wireframes that can help others understand your ideas or the issues being addressed. Visual aids are especially important in design discussions.

## Impact Analysis:
Discuss the potential impact of this issue on the project, including:
How it might affect existing or planned features
Any risks or challenges that could arise
The benefits or improvements it promises

## Related Team Members:
List the team members who should be involved in this discussion.

## Discussion Points:
Explain specific points or questions you want feedback on.

## Proposed Timeline:
If necessary, propose a timeline to discuss this 

## Next Steps:
Explain what you have in your mind to improve the issue situation.

Shortened the template.

**Comment by MertCengiz** [comment]
Is it possible to make this template appear when a member is creating an issue? If yes, could you do it?

**Comment by sametaln** [comment]
I couldn't do that so we can close the issue. We can still copy-paste the template from the codebase.
