### ISSUE TITLE
Create Class Diagrams

### ISSUE THREAD

**Issue by DenizBilgeAkkoc** [bounswe/bounswe2024group7#141]
Title:
Create Class Diagrams

Category:
- [X] Feature Request
- [ ]  Enhancement
- [X]  Design Proposal
- [X]  Specification Clarification
- [ ]  Planning Discussion

Objective:
The objective is to create class diagrams that define the structure and relationships of the software components required for the system. These diagrams will represent the main classes, attributes, methods, and interactions between objects to ensure a clear understanding of the system’s architecture.

**Comment by oguzhekim** [comment]
Initial class diagram is created in the lab w/@MertCengiz. You can review it for further improvements.
