### ISSUE TITLE
Adding User Type Button on Register Web Page

### ISSUE THREAD

**Issue by DenizBilgeAkkoc** [bounswe/bounswe2024group7#155]
Title:
A clear and descriptive title that summarizes the issue.

Description:
A detailed description of the issue. Explain the problem, not just what is happening, but also why it's an issue for your project or workflow.

Steps to Reproduce:
* Step one to reproduce the issue
* Step two...
* (and so on)

Expected Behavior:
Describe what you expected to happen when you executed the steps above.

Actual Behavior:
Adding user type button to web register page to identify user type during register.

Possible Solution:
Updating RegisterComponent.jsx

Your Environment:
* Issue#149
* MacOS 

[Links to similar issues or discussions on GitHub](https://github.com/bounswe/bounswe2024group7/issues/149)

**Comment by sametaln** [comment]
I already add in branch `Issue#149`
