### ISSUE TITLE
Implement Training Program Creation for Trainers (Endpoint)

### ISSUE THREAD

**Issue by m1u1s1** [bounswe/bounswe2024group7#160]
Implement functionality for trainers to create new training programs. 
Acceptance Criteria:
Trainers can submit a new training program through a POST request.
The program is stored with associated details and linked to the trainer who created it.
The response includes the program details and a confirmation of successful creation.

**Comment by sametaln** [comment]
The training program creation endpoints works good. Implemented in the frontend too.
