### ISSUE TITLE
Adding User Profile Page

### ISSUE THREAD

**Issue by DenizBilgeAkkoc** [bounswe/bounswe2024group7#161]
Title:
A clear and descriptive title that summarizes the issue.

Description:
A detailed description of the issue. Explain the problem, not just what is happening, but also why it's an issue for your project or workflow.

Steps to Reproduce:
* Step one to reproduce the issue
* Step two...
* (and so on)

Expected Behavior:
Describe what you expected to happen when you executed the steps above.

Actual Behavior:
Adding user profile page to web.

Possible Solution:
Creating UserProfile component

Your Environment:
* main
* macOs

**Comment by sametaln** [comment]
profile page is completed. Look at the commit [https://github.com/bounswe/bounswe2024group7/commit/59a85199988d9b09ad8bb21a8681ef9b94c4c1c6](url)
