### ISSUE TITLE
 Implement Joining Training Program Functionality

### ISSUE THREAD

**Issue by m1u1s1** [bounswe/bounswe2024group7#171]
Create the functionality for users to join training programs as trainees. 
Acceptance Criteria:

A user should be able to join a training program.
The system should prevent duplicate joins.
The relationship between the user and training program should be stored in the database.

**Comment by sametaln** [comment]
Implemented in the frontend too. We can close now.

[https://github.com/bounswe/bounswe2024group7/commit/59a85199988d9b09ad8bb21a8681ef9b94c4c1c6](url)
