### ISSUE TITLE
Similarize Mobile App With The Website

### ISSUE THREAD

**Issue by MertCengiz** [bounswe/bounswe2024group7#186]
## Title:
Similarize Mobile App With The Website

### Description:
We should convert the mobile components to similar version to the web frontend app. We should adapt UX and UI for this purpose.

### Steps to Reproduce:
* Convert All Mobile Components to Equivalent Pages from Website Components
* Integrate the New Components

### Expected Behavior:
Mobile Application Will Resemble to the Website

### Actual Behavior:
Mobile App Looks Too Different From our Website

### Possible Solution:
Write the Equivalent React Native Components from React Components on the Website

### Your Environment:
* Mobile Directory from "Main" Branch
* Windows 10
* React Native (Using NPM)

### Members:
* Eren Pakelgil @erenpakelgil 
* Mert Cengiz @MertCengiz 

### Labels:
* Mobile
* Priority: High
* Status: In Progress
* Type: Enhancement

**Comment by erenpakelgil** [comment]
New branch lab6 is created and corresponding [PR](#187 ) is created.

**Comment by erenpakelgil** [comment]
Made home page, feed, profile page, post card, create post card component layouts more similar to web frontend UI. Added dark mode. Added create program component. Created a tab display that toggles between create post and program pages. Check corresponding [PR](https://github.com/bounswe/bounswe2024group7/pull/187) for more detail. Review and feedback needed.

**Comment by MertCengiz** [comment]
Related PR merged, closing the issue.
