### ISSUE TITLE
Research about  SPARQL  and semantic queries

### ISSUE THREAD

**Issue by oguzhekim** [bounswe/bounswe2024group7#19]
Conduct a research on SPARQL and semantic queries, which will be important in later stages of our project. A new wikipage will be created under "Researches" section for documenting our research.

**Comment by MertCengiz** [comment]
A brief introduction about SPARQL is made, and two examples are introduced with additioanl resources and references as the new wikipage is created. However, additional information about SPARQL Semantic Queries is a necessity for this page.

**Comment by oguzhekim** [comment]
Added "Why use SPARQL" section. Also reformatted the example queries section using code segment and table features of markdown for better readability. Page is accessible from [here](https://github.com/bounswe/bounswe2024group7/wiki/SPARQL-Semantic-Queries-Tutorial).

**Comment by MertCengiz** [comment]
Added "A General View of a SPARQL Query" section. There are too much information available on the resources in the "Additional Resources and References" part, yet in the future, this tutorial might be expanded related to the needs of the project with the information available on the resources in the "Additional Resources and References" part.

**Comment by oguzhekim** [comment]
Added "Wikidata with SPARQL" section. The research now covers basics of SPARQL as well as its relevance with Wikidata. It is accessible [here](https://github.com/bounswe/bounswe2024group7/wiki/SPARQL-Semantic-Queries-Tutorial). Closing the issue as updates can be addressed by reopening this issue or opening a new one in the future.
