### ISSUE TITLE
Connect the Mobile Application to the Server Side

### ISSUE THREAD

**Issue by MertCengiz** [bounswe/bounswe2024group7#195]
### Title:
Connect the Mobile Application to the Server Side

### Description:
The mobile application is not connected to the server side, all requests are handled statically right now. To add more functionalities, client and server sides shall be connected as the mobile application.

### Steps to Reproduce:
* Connect the endpoints that are coming from the server side to the mobile client.

### Expected Behavior:
Requests from the User Interface are handled by the server side with the help of the database

### Actual Behavior:
Requests are handled in the client side statically. If cannot handled, unnecessary errors are returned.

### Your Environment:
* [Issue 193 Branch](https://github.com/bounswe/bounswe2024group7/issues/193)
* Windows 10, last available version

### Labels:
* Mobile
* Priority: Critical
* Status: In Progress
* Type: Enhancement

**Comment by MertCengiz** [comment]
Related PR is available [here](https://github.com/bounswe/bounswe2024group7/pull/200). As it is merged, closing this issue.

**Comment by erenpakelgil** [comment]
Necessary changes are made, our deployed backend link is used to connect Register and Login with backend using axios library. You can check the related [PR](https://github.com/bounswe/bounswe2024group7/pull/200) for more information.
