### ISSUE TITLE
Research about Linked Data

### ISSUE THREAD

**Issue by Modjak** [bounswe/bounswe2024group7#20]
Conduct a research on Linked Data, which will be important in later stages of our project. A new wikipage will be created under "Researches" section for documenting our research.

**Comment by erenpakelgil** [comment]
Created Linked Data Tutorial wikipage, containing an introduction part followed by its design principles, evaluation of its benefits, some database examples and links to additional resources.

**Comment by Modjak** [comment]
Added 'Challenges and Solutions' and 'Future of Linked Data' part.
