### ISSUE TITLE
Connecting Frontend to Deployed Backend

### ISSUE THREAD

**Issue by hanazaq** [bounswe/bounswe2024group7#210]
## Title:
Connecting Frontend to Deployed Backend

## Description:
I am trying to connect the frontend locally to the deployed backend as specified in the deployed version. Since my laptop cannot handle Docker, I have installed the necessary dependencies locally.

You can find the code at this branch: [issue_192_ProgramPage](https://github.com/bounswe/bounswe2024group7/tree/issue_192_ProgramPage)

## Steps to Reproduce:
1. Run the command: `cd \backend\demo-group7`
2. Run the command: `mvn spring-boot:run`

## Current Behavior:
* Error:  ERROR org.springframework.boot.SpringApplication -- Application run failed  
java.lang.IllegalArgumentException: An instance connection name must be provided in the format `<PROJECT_ID>:<REGION>:<INSTANCE_ID>`.

* The build is successful, but the terminal terminates immediately after.

## Possible Solution:
Please check the `application.properties` in the backend for configuration issues.

## Your Environment:
- Java version: `20.0.2`
- Apache Maven version: `3.8.8` (using Java version `20.0.2`)

**Comment by hanazaq** [comment]
@sametaln @m1u1s1

**Comment by sametaln** [comment]
@m1u1s1 removed the gcp sql dependencies from the pom.xml. This should resolve the issue. @hanazaq

**Comment by hanazaq** [comment]
The frontend in my local is now connected to the deployed backend. (Adding. env under frontend directory was helpful)
