### ISSUE TITLE
Preparing a List of Elicitation Questions

### ISSUE THREAD

**Issue by erenpakelgil** [bounswe/bounswe2024group7#23]
Create a list of questions for customers, which is required in the elicitation part of our first milestone. A new wikipage will be created under "Project" section with title "Elicitation Questions" for documenting our preparation.

**Comment by Modjak** [comment]
Contributed to questions list about wiki-cards

**Comment by MertCengiz** [comment]
Contributed to questions 5-10 (both inclusive) in the list. Double-check from another perspective may be needed.

**Comment by erenpakelgil** [comment]
Contributed to questions 11-20 in the list. Feedback from other group members would be helpful.

**Comment by erenpakelgil** [comment]
Created the wikipage [Elicitation Questions](https://github.com/bounswe/bounswe2024group7/wiki/Elicitation-Questions) containing all questions prepared up until now.

**Comment by sametaln** [comment]
Added questions 21, 22, and 23. Please check.

**Comment by aasimdag** [comment]
Discussed with TA and asked the questions with @oguzhekim @Modjak @erenpakelgil @hanazaq
