### ISSUE TITLE
Feature Request: Add completionDate to UserExerciseDetail

### ISSUE THREAD

**Issue by hanazaq** [bounswe/bounswe2024group7#236]
### Title:
Feature Request: Add completionDate to UserExerciseDetail

### Description:

**Current Response from Backend:**
```
class UserExerciseDetail {
    private Long id;
    private Exercise exercise;
    private int repetitions;
    private int sets;
    private boolean completed;
}
```
**Request:**
Add a completionDate field to track when an exercise was completed:
```
private LocalDate completionDate;
```
**Reason:**
Helps track user progress over time.

**Comment by oguzhekim** [comment]
Reverted completedAt from the exercises as it was causing issues in the deployement. We can work on it for the final milestone

**Comment by hanazaq** [comment]
Thank you, Completed At field has been used in calculating the progress for the current week. More detailed progress tracking section can be provided later.

**Comment by hanazaq** [comment]
Added By Backend Team for the 3rd milestone: @oguzhekim @m1u1s1 @aasimdag
