### ISSUE TITLE
Analyzing 'Paintings' Domain Related Software Systems 

### ISSUE THREAD

**Issue by erenpakelgil** [bounswe/bounswe2024group7#24]
Conduct research on current software systems related to Paintings domain and examining their weaknesses, which will be important in our first milestone. A new wiki page will be created under "Researches" section with title "Domain Analyze" for documenting our research.

**Comment by MertCengiz** [comment]
The first version of the Analysis of Related Software Systems Wiki page is [here](https://github.com/bounswe/bounswe2024group7/wiki/Analysis-of-Related-Software-Systems). This page is written according to the result of [meeting](https://github.com/bounswe/bounswe2024group7/wiki/Meeting-Notes-5) of the related sub-group. All strengths & weaknesses are discussed and examined throughout that meeting. If something is missing, contacting according to the Communication Plan for correction is always possible.

**Comment by MertCengiz** [comment]
No additions needed, the analyze is completed. Closing this issue.
