### ISSUE TITLE
Identify Software Requirements of Paintings' SIB

### ISSUE THREAD

**Issue by hanazaq** [bounswe/bounswe2024group7#25]
1. Identify and specify the requirements of Paintings' semantic information browser (SIB) project.
2. Document the main identified requirements on our project repository using Wiki syntax.
3. Upload supplemental details if needed.

**Comment by oguzhekim** [comment]
Added table of contents and enumerated some of the headings for [requirements page](https://github.com/bounswe/bounswe2024group7/wiki/Requirements).

**Comment by Modjak** [comment]
Added headlines of system requirements to [requirements page](https://github.com/bounswe/bounswe2024group7/wiki/Requirements).

**Comment by MertCengiz** [comment]
Added the contents and enumeration of the Non-Functional Reqirements in the [requirements page](https://github.com/bounswe/bounswe2024group7/wiki/Requirements).

**Comment by Modjak** [comment]
Contributed to System Requirements and wrote questions parts[requirements page](https://github.com/bounswe/bounswe2024group7/wiki/Requirements).

**Comment by oguzhekim** [comment]
Contributed to "User Requirements" section. Also, arranged overall structure of the document.

**Comment by hanazaq** [comment]
Added group discussed requirements to the [requirements' page](https://github.com/bounswe/bounswe2024group7/wiki/Requirements#123-labels).

**Comment by hanazaq** [comment]
Contributed to glossary list content.

**Comment by MertCengiz** [comment]
Requirements are found and its Wiki page is created. Closing this issue.

**Comment by hanazaq** [comment]
Discussed in Teacher elicitation session:
- consider details of search page, personal page, and feed page. 
- can search semantically: discuss semantic restrictions. e.g. search name of artwork, result in list of artworks to the same artist.
