### ISSUE TITLE
Change Training Program Model

### ISSUE THREAD

**Issue by m1u1s1** [bounswe/bounswe2024group7#261]
New columns:
"Type" : ENUM
"LEVEL": ENUM
RATING: [0-5] star (voting would be over discrete values).
Expected Workout duration : int

Training Program would be consist of weeks and workout per weeks. Whole schema will be changed:

### 1. TrainingProgram
- Represents the overall training program.
- **Relationships**:
  - One-to-Many with `Week` (A program consists of multiple weeks).

### 2. Week
- Represents a specific week in the training program (e.g., Week 1, Week 2).
- **Attributes**:
  - `weekNumber`: Numeric identifier for the week.
- **Relationships**:
  - Many-to-One with `TrainingProgram` (Each week belongs to a training program).
  - One-to-Many with `Workout` (Each week includes multiple workouts).

### 3. Workout
- Represents an individual workout session in a specific week.
- **Attributes**:
  - `name`: The name of the workout (e.g., "Chest Press").
  - `description`: Details about the workout (e.g., sets, reps).
  - `duration`: Time in minutes.
  - `muscleGroup`: Targeted muscle group (e.g., Chest, Legs).
- **Relationships**:
  - Many-to-One with `Week` (Each workout belongs to a specific week).

## Diagram

TrainingProgram
    └── Week
            .└── Workout

**Comment by oguzhekim** [comment]
Changed Training Program structure. Details are in [PR#271](https://github.com/bounswe/bounswe2024group7/pull/271).
