### ISSUE TITLE
Mock-up page

### ISSUE THREAD

**Issue by DenizBilgeAkkoc** [bounswe/bounswe2024group7#27]
Adding mock ups for several scenarios and creating its wikipage.

**Comment by DenizBilgeAkkoc** [comment]
[Mock up page](https://github.com/bounswe/bounswe2024group7/wiki/Mock%E2%80%90up-pages-for-scenarios) is created and editted.  Review needed.

**Comment by hanazaq** [comment]
Nice work!
We need to add scenarios for the following also: 
1. creating a post and adding labels to the post.
2. searching by labels. (Check **search** part in the requirements page)
3. showing different results wikidata cards and posts as described in the requirements.

Note: requirements' page does not include save feature mentioned in scenario 1.

**Comment by sametaln** [comment]
Added mock-up design for scenario 6

**Comment by aasimdag** [comment]
Submitted as first deliverable and closing until implementation phase. Well done everyone!
