### ISSUE TITLE
Completing the Customer Milestone Report

### ISSUE THREAD

**Issue by MertCengiz** [bounswe/bounswe2024group7#28]
The Customer Milestone Report is necessary for the project of our group. Creating Titles and Subtitles and completing these parts are essential.

**Comment by sametaln** [comment]
Filled my part of the effort table.

**Comment by hanazaq** [comment]
Filled my part of the effort table.

**Comment by erenpakelgil** [comment]
Filled my part of the effort table and filled Section 4.2.

**Comment by aasimdag** [comment]
Completed and submitted, Congratulations everyone!
