### ISSUE TITLE
Add Progress Graph to Progress Tracker Mechanism

### ISSUE THREAD

**Issue by MertCengiz** [bounswe/bounswe2024group7#292]
### Title:
Add Progress Graph to Progress Tracker Mechanism

### Description:
The mobile application is lacking from a graph that shows the progress to the user. It shall be implemented inside this mobile application.

### Steps to Reproduce:
* Add a graph component to the progress tracking page in the mobile application

### Expected Behavior:
A progress graph is appearing inside the progress tracking page.

### Actual Behavior:
Currently, there is no such graph inside the mobile application.

### Your Environment:
* Main branch, Mobile part
* Windows 10, last version

**Comment by MertCengiz** [comment]
Related PR is available [here](https://github.com/bounswe/bounswe2024group7/pull/293). Reviewer is assigned as Eren @erenpakelgil, and after a successful review, this issue will be closed.

**Comment by erenpakelgil** [comment]
Updated the ProgressTracker and ProgressGraph display, fixed bugs and connected the page with ProfilePage. PR is ready to be merged.
