### ISSUE TITLE
Update Program Creation In Mobile

### ISSUE THREAD

**Issue by MertCengiz** [bounswe/bounswe2024group7#294]
### Title:
Update Program Creation In Mobile

### Description:
Program creation mechanism is outdated right now. It is going to be updated by necessary components and connected with the API.

### Steps to Reproduce:
* Update the endpoints to the new ones coming from the server side.
* Connect necessary components with the API.

### Expected Behavior:
A trainer may create a program with selected exercises.

### Actual Behavior:
Program is tried to be created with the previous logic, which is recently altered.

### Your Environment:
* Local branch copied from `origin/main`
* Windows 10, last version

**Comment by erenpakelgil** [comment]
TrainingProgram component is updated and new version reflects the necessary input fields with a dynamic addition / removal of variable count fields such as weeks, workouts, exercises along with a modal that will be used to select exercises. Backend connection is also established. PR is opened.
