### ISSUE TITLE
Progress Data Not Reflected on Frontend After Successful POST Request

### ISSUE THREAD

**Issue by hanazaq** [bounswe/bounswe2024group7#318]
## Title:
Progress Data Not Reflected on Frontend After Successful POST Request

## Description and Steps to Reproduce:
I am posting the progress of completed sets (e.g., `[10, 8, 9]`) to the backend using the following code in Detailed_Ex_Modal.component.jsx:

```javascript
const response = await apiInstance(sessionToken).post(
  `/api/training-programs/${id}/workout-exercises/${excersizeID}/complete`,
  setInputs
);
```
The data is successfully received by the backend, and the response returned is as expected:
```
{
  "programId": 1,
  "workoutExerciseId": 1,
  "setInputs": [1, 2, 3]
}
```
Afterward, I attempt to view this progress on the frontend by making a GET request to the following endpoint in Training.component:
```
/api/training-programs/joined/${user.username}

```
The response from the backend is correct and contains the relevant data. However, the progress (i.e., the completed sets) is not reflected on the frontend. The backend team has confirmed that the endpoint works as expected, so the issue is likely on the frontend side.
You can find the code at this branch: [TrainingProgramUpdated](https://github.com/bounswe/bounswe2024group7/tree/TrainingProgramUpdated/frontend/src/components)

## Expected Behavior Solution:
The progress of completed sets should be correctly displayed on the page after a successful POST request.

## Current Behavior:
The progress is not displayed on the frontend, even though the backend response is correct.

**Comment by sametaln** [comment]
Solved
