### ISSUE TITLE
Creating Sequence Diagram #3 Search

### ISSUE THREAD

**Issue by Modjak** [bounswe/bounswe2024group7#34]
Creating a sequence diagram of an user trying to search from Wikidata api.

**Comment by MertCengiz** [comment]
The first version of the Third Sequence Diagram related to registration is avaliable [here](https://github.com/bounswe/bounswe2024group7/blob/main/Sequence%20Diagram-3-Make-Search.mmd). Review needed and highly recommended.

**Comment by oguzhekim** [comment]
I have revised the search sequence diagram according to the feedback from TA. These are the changes I have made:
* Removed User and Search. Added Interface and System instead.
* Added a self-returning arrow to System to show the creation of WikidataResult from the API response.

The new diagram is available [here](https://github.com/bounswe/bounswe2024group7/wiki/Sequence-Diagrams), along with the other sequence diagrams.
