### ISSUE TITLE
Create Sequence Diagram: #4 create post and add label.

### ISSUE THREAD

**Issue by hanazaq** [bounswe/bounswe2024group7#37]
Create Sequence Diagram covers create post including add label use case. 
Reference to [Use Case Diagram](https://github.com/bounswe/bounswe2024group7/blob/main/UseCaseDiagram.pdf ).

**Comment by hanazaq** [comment]
https://github.com/bounswe/bounswe2024group7/wiki/Sequence-Diagrams
completed by team's member contribution.

**Comment by erenpakelgil** [comment]
Converted the label "createNewPost(post)" to "createNewPost(image,label_list,description)", "createNewPost(image,label_list,location)" to "createNewPost(user,image,label_list,description)".
