### ISSUE TITLE
Updating Project Plan

### ISSUE THREAD

**Issue by oguzhekim** [bounswe/bounswe2024group7#45]
We need to revise and update our project plan to reflect the requirements of the upcoming milestone 2. The updated plan will replace the previous plan [on this wikipage](https://github.com/bounswe/bounswe2024group7/wiki/Project-Plan).

**Comment by oguzhekim** [comment]
Project plan is updated and it is accessible [here](https://github.com/bounswe/bounswe2024group7/wiki/Project-Plan). I tried to show the tasks we have done so far, and tasks we will do for the second and final milestones. Let me know if you want to make changes on the plan.

**Comment by MertCengiz** [comment]
The dates and task names are accurate and this updated version covers all tasks that must be completed. It seems there is no need to make alterations. Therefore closing this issue. If any change needed, reopen this issue again. Thank you @oguzhekim
