### ISSUE TITLE
Create Sequence Diagram #8: Comment on a Post

### ISSUE THREAD

**Issue by MertCengiz** [bounswe/bounswe2024group7#50]
Create a sequence diagram covering a registered user commenting on a post. Reference: [Use Case Diagram](https://github.com/bounswe/bounswe2024group7/blob/main/UseCaseDiagram.pdf).

**Comment by erenpakelgil** [comment]
The diagram is completed and can be accessible via [here](https://github.com/bounswe/bounswe2024group7/wiki/Sequence-Diagrams). Review needed.
