### ISSUE TITLE
Add Database Tables to the Back-end Part

### ISSUE THREAD

**Issue by MertCengiz** [bounswe/bounswe2024group7#55]
Using Django framework, add the tables created in the [Class Diagram](https://github.com/bounswe/bounswe2024group7/wiki/Class-Diagram-v2) and the [Database Diagram](https://www.figma.com/file/Vr1ilWxTMsT1MpysVJrwKZ/Group7---DB?type=whiteboard&node-id=0-1) to the back-end part with the help of the features that this framework provides.

**Comment by erenpakelgil** [comment]
Converted the tables created in the [Class Diagram](https://github.com/bounswe/bounswe2024group7/wiki/Class-Diagram-v2) and [ER Diagram](https://www.figma.com/file/Vr1ilWxTMsT1MpysVJrwKZ/Group7---DB?type=whiteboard&node-id=0-1&t=UuCQ2jPSKL9P9Poc-0) into django database models and added them into the backend part. Review needed.

**Comment by erenpakelgil** [comment]
Created a new branch including the modified models file according to the [branch name template](https://github.com/bounswe/bounswe2024group7/issues/41) and pushed the branch to the original repository.

**Comment by sametaln** [comment]
We should create PR for the review and merge with `backend` branch

**Comment by sametaln** [comment]
Merged this branch with our backend.
