### ISSUE TITLE
Initialize Mobile Applicaiton

### ISSUE THREAD

**Issue by hanazaq** [bounswe/bounswe2024group7#58]
Initialize Home, sign in, and sign up pages for Artifact mobile application using React Native. 
Sign in and sign up pages receiving username and password as inputs. 
Have the ability to navigate through pages.

**Comment by sametaln** [comment]
Can you open a PR for us to review the code

**Comment by hanazaq** [comment]
Review the code here: https://github.com/bounswe/bounswe2024group7/tree/issue%2358-Initialize-Mobile-Applicaiton

**Comment by sametaln** [comment]
Mobile application is initialized and merged with the rest of the application.
