### ISSUE TITLE
Add Wikidata Queries To Backend

### ISSUE THREAD

**Issue by erenpakelgil** [bounswe/bounswe2024group7#60]
Create wikidata query requests for retrieving relevant data based on the user's input in the scope of semantic search and integrate them into backend application

**Comment by erenpakelgil** [comment]
Created functions that fetch painting items existing in WikiData API based on painting name and art movement using SPARQL in Python with @MertCengiz. Implementing semantic search based on genre and material is upcoming.

**Comment by MertCengiz** [comment]
Used Python as the endpoint for SPARQL queries, created a [new branch](https://github.com/bounswe/bounswe2024group7/tree/issue%2360-add-wikidata-queries) and a [pull request](https://github.com/bounswe/bounswe2024group7/pull/61) with @erenpakelgil.  Review needed.
