### ISSUE TITLE
Improve Semantic Search Feature

### ISSUE THREAD

**Issue by erenpakelgil** [bounswe/bounswe2024group7#79]
Improving our semantic search algorithm is essential since our current algorithm sends a SPARQL query matching the exact form of given input while avoiding other relevant paintings with a name, genre field or movement field that differs slightly from the keyword string.

**Comment by erenpakelgil** [comment]
Created a separate search.py file on the root folder that serves to test the modified outputs on a new branch. Review and feedback needed.

**Comment by MertCengiz** [comment]
New features are added to the search queries and a pull request is created for the branch [issue#75-improve-semantic-search-feature](https://github.com/bounswe/bounswe2024group7/pull/89).

**Comment by erenpakelgil** [comment]
Added related search feature to search.py in (#89) that follows a non-recursive procedure by returning painting results with the same creator as the original results for given keyword.
