### ISSUE TITLE
Designing Meeting Notes section

### ISSUE THREAD

**Issue by aasimdag** [bounswe/bounswe2024group7#8]
Create the wiki page for organizing the meeting notes.

- Allow updating weekly
- Make it seem understandable and user friendly
- Add links if necessary
- Check the previously designed meeting notes pages for references

**Comment by aasimdag** [comment]
Added the templates for meeting notes. Check [Meeting Notes](./Meeting-Notes)

**Comment by oguzhekim** [comment]
Modified "Outcomes" section according to the feedback from the lecture. Please review and edit if anything is missing.

**Comment by MertCengiz** [comment]
Added all participants in our group and a new section containing the decisions of the meeting except action items

**Comment by hanazaq** [comment]
Update Action Items from list to table format for easier reading.

**Comment by aasimdag** [comment]
Updated the Action Items as table and added an example to the [Meeting Notes Template](../wiki/Meeting-Notes-Template)

**Comment by aasimdag** [comment]
Closing the issue until new suggestions to add to the template are given.
