### ISSUE TITLE
Create Customer Milestone Report - 2

### ISSUE THREAD

**Issue by MertCengiz** [bounswe/bounswe2024group7#88]
Title:
Customer Milestone Report - 2

Category:
- [ ] Feature Request
- [ ]  Enhancement
- [ ]  Design Proposal
- [x]  Specification Clarification
- [ ]  Planning Discussion

Objective:
To write the Customer Milestone Report -2, similar to the [First Customer Milestone Report](https://github.com/bounswe/bounswe2024group7/wiki/Customer-Milestone-1-%E2%80%90-Project-Deliverable)

Related Team Members:
List the team members who should be involved in this discussion.

Proposed Timeline:
It is going to be completed on May, 3rd

**Comment by MertCengiz** [comment]
The first version of the [second cudtomer milestone report](https://github.com/bounswe/bounswe2024group7/wiki/Customer-Milestone-2-%E2%80%90-Project-Deliverable) is right now available. There are two sub-parts except personal efforts section are missing.

**Comment by erenpakelgil** [comment]
The final version of the [second customer milestone report](https://github.com/bounswe/bounswe2024group7/wiki/Customer-Milestone-2-%E2%80%90-Project-Deliverable) is complete and submitted to Moodle on 03.05.2024.
