### ISSUE TITLE
Documenting repositories we like

### ISSUE THREAD

**Issue by oguzhekim** [bounswe/bounswe2024group7#9]
We should document some github repositories that we like. If you want to contribute, you can edit [this](https://github.com/bounswe/bounswe2024group7/wiki/Our-Favourite-Repositories) page to write a brief explanation about the repository and what you liked about it. Also, feel free to assign yourself to the issue when you contribute.

**Comment by oguzhekim** [comment]
Added public-apis repository.

**Comment by erenpakelgil** [comment]
Added awesome-python repo

**Comment by Modjak** [comment]
Added Pandas

**Comment by sametaln** [comment]
Unassigned myself for personal research issue.

**Comment by MertCengiz** [comment]
Updated Mert Cengiz's Favourite Repository to the correct form

**Comment by sametaln** [comment]
Didn't we complete this issue? I think we can close this now. @oguzhekim
