### ISSUE TITLE
Discussing About the Order of Priority Among Tasks

### ISSUE THREAD

**Issue by erenpakelgil** [bounswe/bounswe2024group7#91]
We should discuss on which tasks will be implemented first, create an order of priority among them and inform the instructor and assistants about it.

**Comment by MertCengiz** [comment]
The priorities among tasks are discussed in the last [meeting](https://github.com/bounswe/bounswe2024group7/wiki/Meeting-Notes-%2313), and the prioritised tasks are available on the notes of that meeting, which is also send to the TA and the Instructor via Discord
