### ISSUE TITLE
Make API Calls From Mobile Application

### ISSUE THREAD

**Issue by MertCengiz** [bounswe/bounswe2024group7#95]
## Title:
Make API Calls From Mobile Application

## Category:
- [x] Feature Request
- [ ] Enhancement
- [ ] Design Proposal
- [ ] Specification Clarification
- [ ] Planning Discussion

## Objective:
To be able to send and receive requests and data from the backend side, and hence the database.

### Overview
Currently, the mobile application uses mock data. It is a necessity for being able to use actual data coming from the database provided by the backend side.

### Proposed Restructuring:
1. **Adding a New JSON Object**:
   - Create a new object named "formData" within the mobile project directory.
   - Request all necessary information and display it to the UI.

### Implementation Considerations:
- Update api.js file in order to be able to make the calls.
- Review and refactor existing code as necessary to maintain consistency and adherence to best practices.

**Comment by MertCengiz** [comment]
Right now we are able to make search on mobile even though we can only display them on console. Similarly, a user not included in the database cannot enter (A login error displayed) and after signing up, logging in is possible. Its [pull request](https://github.com/bounswe/bounswe2024group7/pull/97) and [branch](https://github.com/bounswe/bounswe2024group7/tree/issue%2395-make-api-calls-mobile) are available. Review needed.

**Comment by m1u1s1** [comment]
Project Archived.
