### ISSUE TITLE
Connect SearchResult to Backend

### ISSUE THREAD

**Issue by erenpakelgil** [bounswe/bounswe2024group7#99]
## Title:
Connect SearchResult to Backend

## Category:
- [x] Feature Request
- [ ] Enhancement
- [ ] Design Proposal
- [ ] Specification Clarification
- [ ] Planning Discussion

## Objective:
To be able to fetch search results from the search endpoint of our API, parse it and render it as a SearchResult component.

### Overview
Currently, the frontend application uses mock data. It is a necessity for being able to use actual data coming from Wikidata API provided by the backend side.

### Proposed Restructuring:
1. **Adding a New JSON Object**:
   - Create a new object named "formData" within the mobile project directory.
   - Request all necessary information and display it to the UI.

### Implementation Considerations:
- Create searchResults, searchResult, postView components 
- Instead of using separate useState functions in these components, pass searchResults data from main navigation page to these components

**Comment by erenpakelgil** [comment]
Linked SearchResult to search endpoint of backend. See #100

**Comment by m1u1s1** [comment]
Project Archived.
